#include <stdio.h>
#include <stdlib.h>
#include <time.h>

void clearScreen(){
      #ifdef _WIN32
            system("cls");
      #else 
            system("clear"); 
      #endif
}

int main(){

      clearScreen();
      // pseudo random number generator = a set of values or elements that are statistically random, but are generated by a deterministic process. 

      srand(time(0)); //seed random number generator
      int randomNumber = rand() % 6 +1 ; //1-6 

      printf("\n%d\n\n", randomNumber);


      return 0;
}
